name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1.3
        with:
          otp-version: "23.0"
          elixir-version: "1.10.3"
      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: MIX_ENV=test mix deps.compile
      - run: MIX_ENV=test mix compile --warnings-as-errors
      - run: mix format --check-formatted
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db:
          - mysql:5.6
          - mysql:5.7
          - mysql:8.0
          - mariadb:10.3
        pair:
          - elixir: "1.10"
            erlang: "23.0"
        include:
          - db: mysql:8.0
            pair:
              elixir: "1.6.6"
              erlang: "19.3.6.13"
    env:
      DB: ${{matrix.db}}
      MYSQL_UNIX_PORT: /var/run/mysqld/mysqld.sock
    steps:
      - run: sudo mkdir -p /var/run/mysqld
      - run: sudo chmod 777 /var/run/mysqld
      - run: docker run -p 3306:3306 --volume /var/run/mysqld:/var/run/mysqld -e MYSQL_ALLOW_EMPTY_PASSWORD=1 --detach ${{matrix.db}} --innodb_log_file_size=1G
      - run: until mysql --port 3306 --protocol=tcp -u root -e "SELECT @@version;"; do sleep 3; done
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.3
        with:
          otp-version: ${{matrix.pair.erlang}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile
      - run: MIX_ENV=test mix compile
      - run: mix test
